### ISSUE TITLE
"start" and "end" are reserved keywords

### ISSUE THREAD

**Issue by mattdennewitz** [davidbmitchell/Baseball-PostgreSQL#1]
May I suggest renaming `start` and `end` fields in the `parks` table to `start_date` and `end_date`? They are both reserved words in the SQL standard, and `end` is reserved in Postgres.

Thanks for your work!

**Comment by davidbmitchell** [comment]
Definitely and I noticed in the `players` table I used `first` and `last` for first names and last names, respectively. These are also reserved words so I fixed these. Thank you. I really appreciate the input.
